name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: basePage.war
        path: /home/runner/work/RockPaperServer/RockPaperServer/target/basePage*.war
